name: Mirroring

on:
  push:
    branches:
      - main
      - master
  delete:

jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
    - uses: https://github.com/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        fetch-depth: 0
    - uses: https://github.com/pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # v1
      with:
        target_repo_url:
          git@github.com:ricariel/ricariel.git
        ssh_private_key:                              # <-- use 'secrets' to pass credential information.
          ${{ secrets.ZYRIA_GITHUB_SSH }}
