---
name: Pre-Commit Checks

on:
  push:
    branches: [main]

jobs:
  call-reusable:
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.zyria.de/pyrox/actions/pre-commit@ccf2c8cd72cc1a31cec10eb5371c2489be6356cf # v1.0
